package ru.majordomo.hms.personmgr.common;


public enum AccountStatType {
    VIRTUAL_HOSTING_PLAN_CHANGE,
    VIRTUAL_HOSTING_PARTNER_PROMOCODE_BALANCE_FILL,
    VIRTUAL_HOSTING_ABONEMENT_DELETE,
    VIRTUAL_HOSTING_ACC_OFF_NOT_ENOUGH_MONEY,
    VIRTUAL_HOSTING_REGISTER_DOMAIN,
    VIRTUAL_HOSTING_MANUAL_RENEW_DOMAIN,
    VIRTUAL_HOSTING_AUTO_RENEW_DOMAIN,
    VIRTUAL_HOSTING_USER_DELETE_ABONEMENT
}
