package ru.majordomo.hms.personmgr.common;


public enum AccountSetting {
    OVERQUOTED,
    ADD_QUOTA_IF_OVERQUOTED,
    POTENTIAL_QUOTA_COUNT,
    AUTO_BILL_SENDING,
    ABONEMENT_AUTO_RENEW,
    CREDIT,
    CREDIT_PERIOD,
    CREDIT_ACTIVATION_DATE,
    NOTIFY_DAYS,
    SMS_PHONE_NUMBER,
    NEW_ACCOUNT,
    CUSTOM_SETTING,
    SBIS_FILIAL
}
