package ru.majordomo.hms.personmgr.common;

/**
 * BusinessActionType
 */
public enum BusinessActionType {
    WEB_SITE_CREATE_RC,
    WEB_SITE_CREATE_MM,
    WEB_SITE_UPDATE_RC,
    WEB_SITE_DELETE_RC,
    DATABASE_CREATE_RC,
    DATABASE_UPDATE_RC,
    DATABASE_DELETE_RC,
    DATABASE_USER_CREATE_RC,
    DATABASE_USER_UPDATE_RC,
    DATABASE_USER_DELETE_RC,
    MAILBOX_CREATE_RC,
    MAILBOX_UPDATE_RC,
    MAILBOX_DELETE_RC,
    PERSON_CREATE_RC,
    PERSON_UPDATE_RC,
    PERSON_DELETE_RC,
}
