package ru.majordomo.hms.personmgr.common;

public enum DocumentType {
    VIRTUAL_HOSTING_OFERTA,
    VIRTUAL_HOSTING_CONTRACT,
    VIRTUAL_HOSTING_BUDGET_CONTRACT,
    VIRTUAL_HOSTING_BUDGET_SUPPLEMENTARY_AGREEMENT,
    VIRTUAL_HOSTING_COMMERCIAL_PROPOSAL,
    VIRTUAL_HOSTING_NOTIFY_RF,
    REGISTRANT_DOMAIN_CERTIFICATE
}