package ru.majordomo.hms.personmgr.common;

/**
 * MailManagerMessageType
 */
public enum MailManagerMessageType {
    SMS_NEW_PAYMENT,
    SMS_NO_MONEY_TO_AUTORENEW_DOMAIN,
    SMS_DOMAIN_DELEGATION_ENDING,
    SMS_REMAINING_DAYS,
    SMS_ABONEMENT_EXPIRING,
    EMAIL_CHANGE_ACCOUNT_PASSWORD,
    EMAIL_CHANGE_FTP_PASSWORD,
    EMAIL_LOGIN_TO_CONTROL_PANEL,
    EMAIL_DOMAIN_DELEGATION_ENDING,
    EMAIL_REMAINING_DAYS,
    EMAIL_NEWS,
    EMAIL_BILLING_DOCUMENTS,
    TELEGRAM_NEW_PAYMENT,
    TELEGRAM_NO_MONEY_TO_AUTORENEW_DOMAIN,
    TELEGRAM_DOMAIN_DELEGATION_ENDING,
    TELEGRAM_REMAINING_DAYS,
    TELEGRAM_ABONEMENT_EXPIRING
}
