package ru.majordomo.hms.personmgr.common;


public enum NotificationType {
//    PLAN_CHANGE,
//    PARTNER_PROMOCODE_BALANCE_FILL,
//    ABONEMENT_DELETE,
    ACC_OFF_NOT_ENOUGH_MONEY,
    REMAINING_DAYS_MONEY_ENDS
//    REGISTER_DOMAIN,
//    MANUAL_RENEW_DOMAIN,
//    AUTO_RENEW_DOMAIN,
//    USER_DELETE_ABONEMENT,
//    FIRST_REAL_PAYMENT
}
