package ru.majordomo.hms.personmgr.common;

public enum SeoType {
    AUDIT,
    CONTEXT,
    CONTEXT_PREMIUM,
    VK_PREMIUM,
    AUDIT_QUALITY,
    AUDIT_ADVERTISEMENT,
    CONTEXT_GOOGLE_AND_YANDEX,
    CONTEXT_GOOGLE_AND_YANDEX_PREMIUM,
    FACEBOOK_PREMIUM,
    INSTAGRAM_PREMIUM,
    TWO_SOCIAL_CHOOSE
}
