# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker-registry.intr/user/javabox

before_script:
  - echo `pwd`
  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE"
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - build
  - push

build:
  stage: build
  script:
    - ./gradlew buildDocker

push:
   stage: push
   script:
     - ./push

after_script:
  - echo "End CI"
