logging:
    level:
        org:
            springframework:
                web: ERROR
                security: ERROR
                data:
                    mongodb:
                        core:
                            MongoTemplate: ERROR
                            MongoOperations: ERROR
        ru:
            majordomo:
                hms:
                    personmgr:
                        service:
                            FinFeignClient: ERROR
                        controller:
                            amqp:
                                AmqpPersonController: ERROR
                                AmqpUnixAccountController: ERROR
security:
    oauth2:
        resource:
            jwt:
#                key-uri: http://localhost:8080/si/si/oauth/token_key
                key-value: |
                    -----BEGIN PUBLIC KEY-----
                    ***REMOVED***
                    -----END PUBLIC KEY-----
            preferTokenInfo: true
#            token-info-uri: http://localhost:8080/si/si/oauth/check_token
        client:
            clientId: service
            clientSecret: service_secret
            accessTokenUri: http://api-dev.intr/oauth/token
            grant-type: password
            scope: service
    sessions: STATELESS
server:
    port: 8070
spring:
    application:
        name: pm
    data:
        mongodb:
#            uri: mongodb://personmgr:***REMOVED***@hms01.intr:27017,hms02.intr:27017,hms03.intr:27017/personmgr?replicaSet=hms-rs0
            uri: mongodb://ci.intr:27017/personmgr
            database: personmgr
#            uri: mongodb://localhost:27017/personmgr
    rabbitmq:
#        host: 172.16.104.98
        host: localhost
        password: guest
        username: guest
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss

management:
  port: 18083
  security:
    enabled: false

endpoints:
  sensitive: false

datasource:
    billing:
        driver-class-name: com.mysql.jdbc.Driver
        password: ***REMOVED***
        url: jdbc:mysql://staff.intr/BillingDB
        username: root
    billing2:
        driver-class-name: com.mysql.jdbc.Driver
        password: ***REMOVED***
        url: jdbc:mysql://staff.intr/billing
        username: root
    partners:
        driver-class-name: com.mysql.jdbc.Driver
        password: ***REMOVED***
        url: jdbc:mysql://staff.intr/partners
        username: root

mail_manager:
    dev_email: web-script@majordomo.ru
    pro_email: web-script@majordomo.ru
    password: ***REMOVED***
    service_message_api_name: RegistrantServiceMessage
    url: http://mailing_manager.dolnigin.dev.majordomo.ru/app_dev.php/api/
    username: api_user

si_oauth:
    serviceUsername: service
    servicePassword: ***REMOVED***
