logging:
    level:
        org:
            springframework:
                web: ERROR
                security: ERROR
                data:
                    mongodb:
                        core:
                            MongoTemplate: ERROR
                            MongoOperations: ERROR
        ru:
            majordomo:
                hms:
                    personmgr:
                        service:
                            FinFeignClient: ERROR
                        controller:
                            amqp:
                                AmqpPersonController: ERROR
                                AmqpUnixAccountController: ERROR
security:
    oauth2:
        resource:
            jwt:
#                key-uri: http://localhost:8080/si/si/oauth/token_key
                key-value: |
                    -----BEGIN PUBLIC KEY-----
                    ***REMOVED***
                    -----END PUBLIC KEY-----
            preferTokenInfo: true
#            token-info-uri: http://localhost:8080/si/si/oauth/check_token
        client:
            clientId: service
            clientSecret: service_secret
            accessTokenUri: http://localhost:8080/oauth/token
            grant-type: client_credentials
            scope: service
    sessions: STATELESS
server:
    port: 8070
spring:
    application:
        name: pm
    data:
        mongodb:
            uri: mongodb://personmgr:***REMOVED***@172.16.104.110:27017,172.16.104.111:27017,172.16.104.112:27017/personmgr?replicaSet=hms-rs0
            database: personmgr
#            uri: mongodb://localhost:27017/personmgr
    rabbitmq:
#        host: 172.16.104.98
        host: localhost
        password: guest
        username: guest
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss